credentials:
  usernames:
    admin:
      email: graham.cassel@envistaco.com
      name: Graham Cassel
      password: Orascoptic2025!  # Plain text - auto-hashed on first run

cookie:
  expiry_days: 30
  key: envista_secure_key_2025_change_this  # Change to random string
  name: envista_cookie

preauthorized:
  emails:
    - graham.cassel@envistaco.com  # Admin pre-approved

# Domain restriction: Only @envistaco.com can register/login
registration:
  allowed_domains:
    - envistaco.com
