credentials:
  usernames:
    orascoptic:
    email: graham.cassel@envistaco.com
    name: Graham
    Password: OrascopticBetaPrice2025!

cookie:
  expiry_days: 30
  key: orascoptic_key_1
  name: ora_cookie

Preauthorized
  emails:
    - graham.cassel@envistaco.com

registration:
  allowed_domains:
    - envistaco.com
