credentials:
  usernames:
    admin:
      email: graham.cassel@envistaco.com
      name: Graham Cassel
      Password: $2b$12$Ztx6DN4LKCQwaX4yHaokVu2Gukmuuj0ibunUo8PG1s5/r0ENg2Wvu

cookie:
  expiry_days: 30
  key: envista_secure_key_ora_1
  name: envista_cookie

Preauthorized
  emails:
    - graham.cassel@envistaco.com

registration:
  allowed_domains:
    - envistaco.com
